In [17]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [32]:
%cd /content/drive/MyDrive/2026-06-02_pet-project_forecasting-customer-churn/forecasting_customer_churn

/content/drive/MyDrive/2026-06-02_pet-project_forecasting-customer-churn/forecasting_customer_churn

In [33]:
!pwd

/content/drive/MyDrive/2026-06-02_pet-project_forecasting-customer-churn/forecasting_customer_churn

In [28]:
import os
from google.colab import userdata

# Получаем токен из секретов Colab
TOKEN = userdata.get('GITHUB_TOKEN')
USER = 'helloqpworld'
REPO = 'forecasting_customer_churnforecasting_customer_churn'

# Формируем безопасный URL для пуша
# repo_url = f"https://{USER}:{TOKEN}@://github.com{USER}/{REPO}.git"

In [36]:
# !git clone https://github.com/helloqpworld/forecasting_customer_churn.git

On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	notebooks/

nothing added to commit but untracked files present (use "git add" to track)

In [ ]:
# Выполняем пуш через системную команду (f-строка передает скрытый токен)
# !git remote set-url origin {repo_url}
!git push origin main

In [ ]:
import os
if not os.path.exists('response_sample.csv'):
    from google.colab import userdata
    os.environ['KAGGLE_USERNAME'] = userdata.get('KAGGLE_USERNAME')
    os.environ['KAGGLE_KEY'] = userdata.get('KAGGLE_KEY')
    ! kaggle competitions download -c findata-response
    ! unzip -q findata-response.zip
    !rm -f responce_sample.csv responce_train.csv findata-response.zip

Downloading findata-response.zip to /content
100% 2.75M/2.75M [00:00<00:00, 249MB/s]

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as ex
import plotly.graph_objs as go
import plotly.figure_factory as ff
from plotly.subplots import make_subplots
import plotly.offline as pyo
pyo.init_notebook_mode()
sns.set_style('darkgrid')
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score as f1
from sklearn.metrics import confusion_matrix

plt.rc('figure',figsize=(18,9))
%pip install -q imbalanced-learn
from imblearn.over_sampling import SMOTE

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
df_train = pd.read_csv('response_train.csv')
df_sample = pd.read_csv('response_sample.csv')

In [ ]:
df_train.shape

(25101, 52)

In [ ]:
df_train.iloc[:, :12].head(1)

,client_id,target,age,job-status,retrirement-status,gender,children,dependants,education,marital-status,industry,title
0,985668,0,41,1,0,1,3,1,Среднее специальное,Состою в браке,Развлечения/Искусство,Работник сферы услуг

In [ ]:
df_train.iloc[:, 12:24].head(1)

,tp-state,tp-foreign,job-type,family-income,personal-income,registration-region,fact-region,postal-region,last-loan-region,region,reg-and-fact-equality,post-and-fact-equality
0,Государственная комп./учреж.,Без участия,Участие в основ. деятельности,от 10000 до 20000 руб.,5600.0,Чувашия,Чувашия,Чувашия,Чувашия,ПРИВОЛЖСКИЙ,1,1

In [ ]:
df_train.iloc[:, 24:41].head(1)

,reg-and-post-equality,reg-fact-and-post-equality,reg-fact-post-and-last-credit-equality,realty,cars,rus-auto,dacha,cottage,garage,land,last-loan-amount,term,first-payment,driving-license,state-pension-fund,residence-time,work-time
0,1,1,1,0,0,0,0,0,0,0,13000.0,12,4000.0,0,1,144,24.0

In [ ]:
df_train.iloc[:, 41:].head(1)

,fact-phone,reg-phone,work-phone,loans,paid-loans,total-payments,total-of-delinquencies,max-delinquency-no,mean-delinquency-amount,max-delinquency-amount,previous-cards
0,0,0,1,1,0,3,0,0,0.0,0.0,NaN

In [ ]:
# НАШЕЛ ВЫБРОС В RESIDENCE-TIME. В PREVIOUS-CARDS МНОГО Nan

# Был выброс в residence-time равный -26, я заменил на 0
df_train.loc[3399, 'residence-time'] = 0

# Почти все значения previous-cards (количество карт с завершенным сроком использования) как Nan, их заменил на 0
df_train['previous-cards'] = df_train['previous-cards'].fillna(0)

# Все значения равны 0, поэтому удалил столбец
del df_train['driving-license']

In [ ]:
df_train.info(memory_usage='deep', show_counts=True, verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25101 entries, 0 to 25100
Columns: 51 entries, client_id to previous-cards
dtypes: float64(7), int64(31), object(13)
memory usage: 39.6 MB

In [ ]:
categorical_cols = df_train.select_dtypes(include=['object', 'category']).columns
numeric_cols = df_train.select_dtypes(include=['int', 'float']).columns
print(f'Категориальные ({len(categorical_cols)}) + Числовые ({len(numeric_cols)}) = Всего ({len(categorical_cols) + len(numeric_cols)})')

Категориальные (13) + Числовые (38) = Всего (51)

In [ ]:
for col in df_train.select_dtypes(include=['object', 'category']).columns:
    df_train[col] = df_train[col].astype('category')

In [ ]:
df_train.info(memory_usage='deep', show_counts=True, verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25101 entries, 0 to 25100
Columns: 51 entries, client_id to previous-cards
dtypes: category(12), float64(7), int64(31), int8(1)
memory usage: 7.6 MB

In [ ]:
print(f"Количество полных дубликатов: {df_train.duplicated().sum()}")
# Подсчет пропущенных значений в процентах по каждой колонке
missing_values = df_train.isnull().sum()
missing_percent = (missing_values / len(df_train)) * 100

# Объединяем в красивую таблицу (выводим только те колонки, где есть пропуски)
missing_df = pd.DataFrame({'Пропуски (шт)': missing_values, 'Пропуски (%)': missing_percent})
missing_df[missing_df['Пропуски (шт)'] > 0].sort_values(by='Пропуски (%)', ascending=False)

Количество полных дубликатов: 0

                  Пропуски (шт)  Пропуски (%)
work-time                  2262      9.011593
industry                   2259      8.999641
tp-state                   2259      8.999641
title                      2259      8.999641
job-type                   2259      8.999641
tp-foreign                 2255      8.983706
last-loan-region            491      1.956097
region                        2      0.007968

In [ ]:
df_train.describe().loc[['count', 'min', '50%', 'max']].T

,count,min,50%,max
client_id,25101.0,985468.0,1000545.0,1015599.0
target,25101.0,0.0,0.0,1.0
age,25101.0,21.0,39.0,67.0
job-status,25101.0,0.0,1.0,1.0
retrirement-status,25101.0,0.0,0.0,1.0
gender,25101.0,0.0,1.0,1.0
children,25101.0,0.0,1.0,10.0
dependants,25101.0,0.0,0.0,7.0
personal-income,25101.0,24.0,12000.0,13000000.0
reg-and-fact-equality,25101.0,0.0,1.0,1.0
post-and-fact-equality,25101.0,0.0,1.0,1.0
reg-and-post-equality,25101.0,0.0,1.0,1.0
reg-fact-and-post-equality,25101.0,0.0,1.0,1.0
reg-fact-post-and-last-credit-equality,25101.0,0.0,1.0,1.0
realty,25101.0,0.0,0.0,1.0
cars,25101.0,0.0,0.0,2.0
rus-auto,25101.0,0.0,0.0,1.0
dacha,25101.0,0.0,0.0,1.0
cottage,25101.0,0.0,0.0,1.0
garage,25101.0,0.0,0.0,1.0
land,25101.0,0.0,0.0,1.0
last-loan-amount,25101.0,1843.0,11489.0,150000.0
term,25101.0,3.0,6.0,36.0
first-payment,25101.0,0.0,2000.0,140000.0
state-pension-fund,25101.0,0.0,1.0,1.0
residence-time,25101.0,0.0,108.0,48215880.0
work-time,22839.0,1.0,48.0,10000.0
fact-phone,25101.0,0.0,1.0,1.0
reg-phone,25101.0,0.0,0.0,1.0
work-phone,25101.0,0.0,1.0,1.0
loans,25101.0,1.0,1.0,11.0
paid-loans,25101.0,0.0,0.0,11.0
total-payments,25101.0,1.0,5.0,114.0
total-of-delinquencies,25101.0,0.0,0.0,13.0
max-delinquency-no,25101.0,0.0,0.0,8.0
mean-delinquency-amount,25101.0,0.0,0.0,28012.2
max-delinquency-amount,25101.0,0.0,0.0,28012.2
previous-cards,25101.0,0.0,0.0,2.0

In [ ]:
if len(categorical_cols) > 0:
    print(df_train[categorical_cols].describe().T)
else:
    print("\nКатегориальных признаков не найдено.")

                     count unique                            top   freq
education            25101      7            Среднее специальное  10670
marital-status       25101      5                 Состою в браке  15369
industry             22842     31                       Торговля   3958
title                22842     12                     Специалист  11611
tp-state             22842      5               Частная компания  10785
tp-foreign           22846      2                    Без участия  22576
job-type             22842     10  Участие в основ. деятельности  18839
family-income        25101      5         от 10000 до 20000 руб.  11643
registration-region  25101     82             Краснодарский край   1098
fact-region          25101     83             Краснодарский край   1101
postal-region        25101     82             Краснодарский край   1100
last-loan-region     24610     70             Краснодарский край   1300
region               25099     11                          ЮЖНЫЙ   3551

In [ ]:
df_train['target'].value_counts().reset_index().assign(total_sum = lambda x: x['count'].sum(), percentage = lambda x: (x['count'] / x['count'].sum()) * 100).round(2)

   target  count  total_sum  percentage
0       0  22081      25101       87.97
1       1   3020      25101       12.03

In [ ]:
import scipy.stats as stats
from scipy.stats import chi2_contingency

In [ ]:
for col in categorical_cols:
    contingency_table = pd.crosstab(df_train[~df_train.isna().any(axis=1)][col], df_train[~df_train.isna().any(axis=1)]['target'])
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    if p < 0.01:
        print(f"✅ p-value = {p:.4f} признак {col}")
    else:
        print(f"❌ p-value = {p:.4f} признак {col}")

✅ p-value = 0.0000 признак education
✅ p-value = 0.0003 признак marital-status
✅ p-value = 0.0000 признак industry
✅ p-value = 0.0001 признак title
✅ p-value = 0.0000 признак tp-state
❌ p-value = 0.3865 признак tp-foreign
❌ p-value = 0.7658 признак job-type
✅ p-value = 0.0000 признак family-income
✅ p-value = 0.0000 признак registration-region
✅ p-value = 0.0000 признак fact-region
✅ p-value = 0.0000 признак postal-region
✅ p-value = 0.0000 признак last-loan-region
✅ p-value = 0.0000 признак region

In [ ]:
income_mapping = {
    'до 5000 руб.': 2,
    'от 5000 до 10000 руб.': 8,
    'от 10000 до 20000 руб.': 15,
    'от 20000 до 50000 руб.': 35,
    'свыше 50000 руб.': 100
}
df_train['family-income'] = df_train['family-income'].map(income_mapping).astype('int8')

In [ ]:
# cols_for_del = ['registration-region', 'postal-region', 'last-loan-region', 'region', 'max-delinquency-amount',
#                 'paid-loans', 'reg-fact-and-post-equality', 'reg-and-post-equality', 'retrirement-status',
#                 'total-payments', 'client_id', 'job-status', 'tp-foreign', 'job-type', 'previous-cards', 'work-phone',
#                 'post-and-fact-equality', 'cars', 'rus-auto', 'cottage', 'garage', 'land', 'work-time', 'reg-phone',
#                 'age', 'reg-fact-post-and-last-credit-equality', 'industry', 'title', 'tp-state', 'family-income',
#                 'reg-and-fact-equality', 'last-loan-amount', 'first-payment', 'state-pension-fund', 'residence-time',
#                 'total-of-delinquencies', 'personal-income', 'driving-license']

In [ ]:
%pip install -q phik
import phik
from phik import report

In [ ]:
phik_matrix = df_train[~df_train.isna().any(axis=1)].phik_matrix()

interval columns not set, guessing: ['target', 'age', 'retrirement-status', 'gender', 'children', 'dependants', 'family-income', 'reg-and-post-equality', 'last-loan-amount', 'term', 'first-payment', 'residence-time', 'fact-phone', 'paid-loans', 'total-payments', 'total-of-delinquencies', 'max-delinquency-no', 'mean-delinquency-amount', 'previous-cards']

In [ ]:
styled_matrix = phik_matrix.style.background_gradient(cmap='coolwarm', vmin=0, vmax=1).format("{:.4f}")

# Настраиваем стили: выравнивание и уменьшенный размер текста
styled_matrix = styled_matrix.set_table_styles([
    # Стили для всех ячеек с данными и боковых заголовков строк
    {'selector': 'th, td', 'props': [
        ('font-size', '9px'),           # <-- Уменьшили размер текста (было 12px)
        ('text-align', 'center'),       # <-- Выравнивание по центру (горизонтально)
        ('vertical-align', 'middle'),   # <-- Выравнивание по центру (вертикально)
        ('min-width', '45px'),          # Немного уменьшили ячейки под мелкий шрифт
        ('max-width', '45px'),
        ('height', '45px'),
        ('border', '1px solid #ffffff') # Белая сетка
    ]},
    # Особые стили для верхних заголовков (чтобы они тоже были по центру и мелкими)
    {'selector': 'th.col_heading', 'props': [
        ('font-size', '9px'),           # <-- Мелкий шрифт для верхних названий
        ('text-align', 'center'),       # <-- Центрирование верхних названий
        ('transform', 'rotate(0 deg)'), # Поворот для экономии места
        ('height', '80px'),
        ('vertical-align', 'bottom')
    ]}
])

styled_matrix

In [ ]:
# 0 ЗДЕСЬ ЗАПИСЫВАЕМ СТОЛБЦЫ, КОТОРЫЕ ЯВЛЯЮТСЯ ШУМОМ ДЛЯ ТАРГЕТА
corr_with_target = phik_matrix[phik_matrix['target'] < 0.02]['target'].sort_values().sort_values(ascending=False).reset_index()['index'].values

# 1. Вытаскиваем связь каждого признака с целевой переменной из вашей phik_matrix
target_corr = phik_matrix['target'].abs().drop('target', errors='ignore')
# 2. Получаем только чистую матрицу признаков (без target)
matrix_no_target = phik_matrix.drop(index='target', columns='target', errors='ignore').abs()
# 3. Находим пары с корреляцией > 0.70 (верхний треугольник)
upper_tri = matrix_no_target.where(np.triu(np.ones(matrix_no_target.shape), k=1).astype(bool))
pairs = upper_tri.stack()
strong_pairs = pairs[pairs > 0.8].index.tolist() # получаем список кортежей (Признак_1, Признак_2)
# 4. Проходим по парам и выбираем, кого удалить
to_drop = set()
for col1, col2 in strong_pairs:
    # Если один из признаков уже помечен на удаление, пропускаем шаг
    if col1 in to_drop or col2 in to_drop:
        continue
    # Сравниваем их полезность для target
    score1 = target_corr.get(col1, 0)
    score2 = target_corr.get(col2, 0)
    # Удаляем тот, у которого связь с таргетом слабее
    if score1 < score2:
        to_drop.add(col1)
    else:
        to_drop.add(col2)
print(f"К удалению: корреляция между переменными ({len(to_drop)} шт) между переменной и таргетом ({len(corr_with_target)} шт)")

К удалению: корреляция между переменными (0 шт) между переменной и таргетом (0 шт)

In [ ]:
to_drop_by_corr = list(to_drop) + phik_matrix[phik_matrix['target'] < 0.02]['target'].sort_values().sort_values(ascending=False).reset_index()['index'].values.tolist()
print(len(to_drop_by_corr))

0

In [ ]:
for col in to_drop_by_corr:
    del df_train[col]
print(f"Количество полных дубликатов: {df_train.duplicated().sum()}")

Количество полных дубликатов: 0

In [ ]:
phik_matrix = df_train[~df_train.isna().any(axis=1)].phik_matrix()

styled_matrix = phik_matrix.style.background_gradient(cmap='coolwarm', vmin=0, vmax=1).format("{:.4f}")

# Настраиваем стили: выравнивание и уменьшенный размер текста
styled_matrix = styled_matrix.set_table_styles([
    # Стили для всех ячеек с данными и боковых заголовков строк
    {'selector': 'th, td', 'props': [
        ('font-size', '9px'),           # <-- Уменьшили размер текста (было 12px)
        ('text-align', 'center'),       # <-- Выравнивание по центру (горизонтально)
        ('vertical-align', 'middle'),   # <-- Выравнивание по центру (вертикально)
        ('min-width', '45px'),          # Немного уменьшили ячейки под мелкий шрифт
        ('max-width', '45px'),
        ('height', '45px'),
        ('border', '1px solid #ffffff') # Белая сетка
    ]},
    # Особые стили для верхних заголовков (чтобы они тоже были по центру и мелкими)
    {'selector': 'th.col_heading', 'props': [
        ('font-size', '9px'),           # <-- Мелкий шрифт для верхних названий
        ('text-align', 'center'),       # <-- Центрирование верхних названий
        ('transform', 'rotate(0 deg)'), # Поворот для экономии места
        ('height', '80px'),
        ('vertical-align', 'bottom')
    ]}
])

styled_matrix

interval columns not set, guessing: ['target', 'age', 'retrirement-status', 'gender', 'children', 'dependants', 'family-income', 'reg-and-post-equality', 'last-loan-amount', 'term', 'first-payment', 'residence-time', 'fact-phone', 'paid-loans', 'total-payments', 'total-of-delinquencies', 'max-delinquency-no', 'mean-delinquency-amount', 'previous-cards']

In [ ]:
df_train.info(memory_usage='deep', show_counts=True, verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25101 entries, 0 to 25100
Columns: 25 entries, target to previous-cards
dtypes: category(6), float64(4), int64(14), int8(1)
memory usage: 3.6 MB

In [ ]:
categorical_cols = df_train.select_dtypes(include=['object', 'category']).columns
numeric_cols = df_train.select_dtypes(include=['int8', 'int64', 'float']).columns
print(f'Категориальные ({len(categorical_cols)}) + Числовые ({len(numeric_cols)}) = Всего ({len(categorical_cols) + len(numeric_cols)})')

Категориальные (6) + Числовые (19) = Всего (25)

In [ ]:
print(f"Количество полных дубликатов: {df_train.duplicated().sum()}")
# Подсчет пропущенных значений в процентах по каждой колонке
missing_values = df_train.isnull().sum()
missing_percent = (missing_values / len(df_train)) * 100

# Объединяем в красивую таблицу (выводим только те колонки, где есть пропуски)
missing_df = pd.DataFrame({'Пропуски (шт)': missing_values, 'Пропуски (%)': missing_percent})
missing_df[missing_df['Пропуски (шт)'] > 0].sort_values(by='Пропуски (%)', ascending=False)

Количество полных дубликатов: 0

Empty DataFrame
Columns: [Пропуски (шт), Пропуски (%)]
Index: []

In [ ]:
print(f'{df_train.shape[0]} - 2259 = {df_train.shape[0] - 2259}')
df_train.dropna(inplace=True)
print(df_train.shape[0])

In [ ]:
df_train.head(5)

,target,age,retrirement-status,gender,children,dependants,education,marital-status,industry,title,...,term,first-payment,residence-time,fact-phone,paid-loans,total-payments,total-of-delinquencies,max-delinquency-no,mean-delinquency-amount,previous-cards
0,0,41,0,1,3,1,Среднее специальное,Состою в браке,Развлечения/Искусство,Работник сферы услуг,...,12,4000.0,144,0,0,3,0,0,0.0,0.0
1,0,29,0,1,1,0,Высшее,Разведен(а),Банк/Финансы,Высококвалифиц. специалист,...,12,14000.0,72,1,0,4,0,0,0.0,0.0
2,1,27,0,1,0,0,Среднее специальное,Не состоял в браке,Транспорт,Рабочий,...,10,670.0,95,1,0,8,0,0,0.0,0.0
3,0,26,0,1,0,0,Среднее специальное,Гражданский брак,Информационные услуги,Специалист,...,6,2000.0,36,1,2,7,0,0,0.0,0.0
5,1,34,0,0,2,2,Среднее,Состою в браке,Другие сферы,Специалист,...,6,1207.0,79,1,2,13,0,0,0.0,0.0

In [ ]:
cat_summary = pd.DataFrame({
    'Уникальных': df_train[categorical_cols].nunique(),
    'Пропусков': df_train[categorical_cols].isna().sum()
})
cat_summary.sort_values(by="Уникальных")

                Уникальных  Пропусков
marital-status           5          0
tp-state                 5          0
education                7          0
title                   12          0
industry                31          0
postal-region           81          0

In [ ]:
phik_matrix = df_train[~df_train.isna().any(axis=1)][list(categorical_cols) + ['target']].phik_matrix()

styled_matrix = phik_matrix.style.background_gradient(cmap='coolwarm', vmin=0, vmax=1).format("{:.4f}")

# Настраиваем стили: выравнивание и уменьшенный размер текста
styled_matrix = styled_matrix.set_table_styles([
    # Стили для всех ячеек с данными и боковых заголовков строк
    {'selector': 'th, td', 'props': [
        ('font-size', '11px'),           # <-- Уменьшили размер текста (было 12px)
        ('text-align', 'center'),       # <-- Выравнивание по центру (горизонтально)
        ('vertical-align', 'middle'),   # <-- Выравнивание по центру (вертикально)
        ('min-width', '50px'),          # Немного уменьшили ячейки под мелкий шрифт
        ('max-width', '50px'),
        ('height', '50px'),
        ('border', '1px solid #ffffff') # Белая сетка
    ]},
    # Особые стили для верхних заголовков (чтобы они тоже были по центру и мелкими)
    {'selector': 'th.col_heading', 'props': [
        ('font-size', '11px'),           # <-- Мелкий шрифт для верхних названий
        ('text-align', 'center'),       # <-- Центрирование верхних названий
        ('transform', 'rotate(0 deg)'), # Поворот для экономии места
        ('height', '80px'),
        ('vertical-align', 'bottom')
    ]}
])

styled_matrix

interval columns not set, guessing: ['target']